<?php

/**
 * @file
 * Support for videos as media entities.
 */

use Drupal\entity_browser_generic_embed\OverrideHelper as Override;
use Drupal\entity_browser_video_embed\Plugin\media\Source\Video;

/**
 * Implements hook_media_source_info_alter().
 */
function entity_browser_video_embed_media_source_info_alter(array &$sources) {
  $sources['video_embed_field']['input_match'] = [
    'field_types' => [
      'string',
      'string_long',
      'video_embed_field',
    ],
  ];
  $sources['video_embed_field']['preview'] = TRUE;

  Override::pluginClass($sources['video_embed_field'], Video::class);
}
