<?php

/**
 * @file
 * Support for instagram posts as media entities.
 */

use Drupal\entity_browser_generic_embed\OverrideHelper as Override;
use Drupal\entity_browser_instagram_embed\Plugin\media\Source\Instagram;

/**
 * Implements hook_media_source_info_alter().
 */
function entity_browser_instagram_embed_media_source_info_alter(array &$sources) {
  $sources['instagram']['input_match'] = [
    'constraint' => 'InstagramEmbedCode',
    'field_types' => [
      'string',
      'string_long',
    ],
  ];
  $sources['instagram']['preview'] = TRUE;

  Override::pluginClass($sources['instagram'], Instagram::class);
}
