<?php

/**
 * @file
 * Support for tweets as media entities.
 */

use Drupal\entity_browser_generic_embed\OverrideHelper as Override;
use Drupal\entity_browser_twitter_embed\Plugin\media\Source\Twitter;

/**
 * Implements hook_media_source_info_alter().
 */
function entity_browser_generic_embed_media_source_info_alter(array &$sources) {
  $sources['twitter']['input_match'] = [
    'constraint' => 'TweetEmbedCode',
    'field_types' => [
      'string',
      'string_long',
    ],
  ];
  $sources['twitter']['preview'] = TRUE;

  Override::pluginClass($sources['twitter'], Twitter::class);
}
